const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('/qa/node_modules/playwright');
const messages=require('/source/frontend/src/shared/i18n/messages.json'),terms=require('/source/frontend/src/shared/i18n/gameTerms.json');
const names={en:'English',ko:'한국어','zh-CN':'简体中文 (CN)','zh-TW':'繁體中文 (TW)',ja:'日本語',es:'Español'};
const checks=[],errors=[],measurements=[],filmKey='hephaistos.workbench.films.v1',run=process.env.QA_RUN||'1';let browser,page;
function check(n,v){assert(v,n);checks.push(n)}
async function locale(value){await page.locator('.locale-trigger').click();await page.getByRole('menuitemradio',{name:names[value],exact:true}).click();}
async function measure(){return page.evaluate(()=>({scrollY,documentHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight,width:document.documentElement.scrollWidth,viewportWidth:innerWidth,boxes:Object.fromEntries(['.craft-page','.stash-panel','.stash-board','.stash-canvas','.bench-lower','.workbench-feedback-panel','.craft-footer'].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return [s,{top:r.top+scrollY,bottom:r.bottom+scrollY,height:r.height,marginBottom:parseFloat(getComputedStyle(e).marginBottom)}]}))}));}
async function history(){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)),filmKey)}
async function apply(id){const before=(await history()).cursor;await page.getByRole('tab',{name:messages.en['stash.Currency'],exact:true}).click();await page.getByRole('button',{name:terms.en[id].name,exact:true}).click({button:'right'});await page.locator('.item-slot').click({modifiers:['Shift']});await page.waitForFunction(({filmKey,before})=>JSON.parse(localStorage.getItem(filmKey)).cursor===before+1,{filmKey,before});}
(async()=>{
 browser=await chromium.launch({headless:true});page=await(await browser.newContext({viewport:{width:1440,height:900}})).newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://host.docker.internal:19081',{waitUntil:'networkidle'});
 check('fresh QA profile Korean default',await page.locator('html').getAttribute('lang')==='ko');
 await locale('en');
 // Menu keyboard and focus tests in a real browser.
 const trigger=page.locator('.locale-trigger');await trigger.focus();await page.keyboard.press('ArrowDown');
 check('English focused on open',await page.getByRole('menuitemradio',{name:'English',exact:true}).evaluate(e=>e===document.activeElement));
 check('six locales in required order',JSON.stringify(await page.getByRole('menuitemradio').evaluateAll(es=>es.map(e=>e.lang)))===JSON.stringify(Object.keys(names)));
 await page.keyboard.press('ArrowUp');check('arrow wraps to Spanish',await page.getByRole('menuitemradio',{name:'Español'}).evaluate(e=>e===document.activeElement));
 await page.keyboard.press('Home');await page.keyboard.press('End');await page.keyboard.press('Escape');check('Escape closes and restores focus',await page.getByRole('menu').count()===0&&await trigger.evaluate(e=>e===document.activeElement));
 await trigger.click();await page.locator('h1').click();check('outside dismiss',await page.getByRole('menu').count()===0);
 await trigger.click();await page.keyboard.press('Tab');check('Tab exits menu',await page.getByRole('menu').count()===0&&!await trigger.evaluate(e=>e===document.activeElement));
 // Controls belong to the top of the item affix panel; dialogs retain focus return.
 check('session controls at affix top',await page.locator('.bench-lower > :first-child').getAttribute('class')==='workbench-session-entry');
 check('session controls outside stash viewport',await page.locator('.stash-viewport .workbench-session-entry').count()===0);
 await page.locator('.workbench-session-entry button').first().click();check('select base dialog visible',await page.locator('dialog').isVisible());await page.keyboard.press('Escape');check('base dialog focus restored',await page.locator('.workbench-session-entry button').first().evaluate(e=>e===document.activeElement));
 await page.locator('.workbench-session-entry button').nth(1).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'null')?.films.length>0,filmKey);
 const first=(await history()).active;await page.locator('.workbench-session-entry button').nth(1).click();await page.waitForFunction(({filmKey,first})=>JSON.parse(localStorage.getItem(filmKey)).active!==first,{filmKey,first});check('new craft adds independent film',(await history()).films.length===2);
 await apply('Orb_of_Transmutation');await apply('Orb_of_Augmentation');await apply('Regal_Orb');await apply('Exalted_Orb');
 check('Shift currency use records four frames',(await history()).cursor===4);
 await page.keyboard.down('Alt');check('Alt preserves affix metadata',await page.locator('.bench-item-card .item-card__affix').count()===4);await page.keyboard.up('Alt');
 await page.getByRole('button',{name:messages.en['ui.previous_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===3,filmKey);await page.getByRole('button',{name:messages.en['ui.next_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===4,filmKey);check('undo redo preserved',true);
 const saved=JSON.stringify(await history());await page.reload({waitUntil:'networkidle'});check('film reload exact',JSON.stringify(await history())===saved);
 // Orange local preview stays separate from committing currency.
 await page.getByRole('tab',{name:messages.en['stash.Omen'],exact:true}).click();await page.getByRole('button',{name:terms.en.Omen_of_Whittling.name,exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: empty',exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: '+terms.en.Omen_of_Whittling.name,exact:true}).click({button:'right'});await page.getByRole('tab',{name:messages.en['stash.Currency'],exact:true}).click();await page.getByRole('button',{name:terms.en.Orb_of_Annulment.name,exact:true}).click({button:'right'});
 check('orange preview preserved',await page.locator('.bench-item-card [data-removal-candidate]').count()>0);check('preview does not alter film',JSON.stringify(await history())===saved);await page.keyboard.press('Escape');
 for(const loc of Object.keys(names)){
  await locale(loc);check(loc+' locale persisted',await page.evaluate(()=>localStorage.getItem('hephaistos.locale.v1'))===loc);
  for(const viewport of [{width:1920,height:1080},{width:1440,height:900},{width:1440,height:1100},{width:1440,height:1400},{width:1024,height:768},{width:390,height:844}]){
   await page.setViewportSize(viewport);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(250);
   check(loc+viewport.width+' no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
   const board=await measure();check(loc+viewport.width+' texture scoped to stash',await page.locator('.stash-viewport').evaluate(e=>getComputedStyle(e).backgroundImage.includes('stash-background'))&&!await page.locator('.bench-lower').evaluate(e=>getComputedStyle(e).backgroundImage.includes('stash-background')));
   const slots=page.locator('[data-material-tooltip]');await slots.first().scrollIntoViewIfNeeded();await page.mouse.move(1,1);await page.waitForTimeout(200);
   const samples=[await measure()];
   for(let i=0;i<8;i++){const box=await slots.nth(i).boundingBox();if(!box||box.y<0||box.y+box.height>viewport.height||box.x<0||box.x+box.width>viewport.width)continue;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(80);check(loc+viewport.width+' tooltip body portal '+i,await page.locator('body > .material-tooltip').count()===1);const tip=await page.locator('.material-tooltip').boundingBox();check(loc+viewport.width+' tooltip within viewport '+i,tip&&tip.x>=0&&tip.y>=0&&tip.x+tip.width<=viewport.width+1&&tip.y+tip.height<=viewport.height+1);samples.push(await measure());await page.mouse.move(1,1);await page.waitForTimeout(180);samples.push(await measure());}
   const bottoms=samples.map(s=>s.boxes['.stash-panel'].bottom),shift=Math.max(...bottoms)-Math.min(...bottoms);check(loc+viewport.width+' repeated hover border stable',shift<0.1);
   // Long explanations may scroll within their reserved area, never move its border.
   const before=await measure();await page.getByRole('tab',{name:messages[loc]['stash.Catalysts'],exact:true}).click();await slots.first().click({button:'right'});await page.waitForTimeout(150);const selected=await measure();const feedback=await page.locator('.workbench-feedback-panel').evaluate(e=>({text:e.innerText,clientHeight:e.clientHeight,scrollHeight:e.scrollHeight,tabIndex:e.tabIndex}));check(loc+viewport.width+' feedback keyboard accessible',feedback.tabIndex===0);await page.keyboard.press('Escape');await page.getByRole('tab',{name:messages[loc]['stash.Currency'],exact:true}).click();await page.waitForTimeout(150);const cleared=await measure();check(loc+viewport.width+' selection feedback border stable',Math.abs(before.boxes['.stash-panel'].bottom-selected.boxes['.stash-panel'].bottom)<0.1&&Math.abs(before.boxes['.stash-panel'].bottom-cleared.boxes['.stash-panel'].bottom)<0.1);
   measurements.push({locale:loc,viewport,board,hoverShift:shift,samples,selected,cleared,feedback});
   await page.evaluate(()=>scrollTo(0,0));await page.mouse.move(1,1);await page.waitForTimeout(200);await page.screenshot({path:'/evidence/after-'+loc+'-'+viewport.width+'x'+viewport.height+'.png',fullPage:true});
   if(viewport.width===390||viewport.height===900){await trigger.click();const menu=await page.getByRole('menu').boundingBox();check(loc+viewport.width+' menu fits viewport',menu&&menu.x>=0&&menu.x+menu.width<=viewport.width);await page.screenshot({path:'/evidence/popover-'+loc+'-'+viewport.width+'.png',fullPage:true});await page.keyboard.press('Escape');check(loc+viewport.width+' menu focus restored',await trigger.evaluate(e=>e===document.activeElement));}
  }
 }
 await page.setViewportSize({width:1440,height:900});await locale('en');
 await page.locator('.workbench-session-entry button').first().click();await page.locator('#base-select').selectOption('ring');await page.getByRole('button',{name:messages.en['ui.place_base'],exact:false}).click();await page.waitForFunction(k=>{const h=JSON.parse(localStorage.getItem(k));return h.films.find(f=>f.id===h.active).frames[0].state.baseItemId.includes('Ring')},filmKey);check('base selection starts ring film',await page.locator('.bench-item-card .item-card__header').innerText()==='Iron Ring');
 for(const tab of ['support','explorer','workbench']){await page.getByRole('tab',{name:messages.en['workspace.'+tab],exact:false}).click();check('navigation '+tab,await page.locator('#panel-'+tab).isVisible());}
 await page.waitForLoadState('networkidle');const filmBeforeAdmin=JSON.stringify(await history());const api=[];page.on('request',r=>{if(r.url().includes('/api/'))api.push(r.url())});
 await page.getByRole('link',{name:messages.en['ui.admin'],exact:true}).click();await page.waitForLoadState('networkidle');check('admin real route',new URL(page.url()).pathname==='/admin');check('admin current nav',await page.locator('.workspace-admin').getAttribute('aria-current')==='page');check('admin does not load privileged or crafting API',api.length===0);check('admin has no tools',await page.getByText(messages.en['ui.no_admin_tools_are_available_yet']).isVisible());await page.screenshot({path:'/evidence/after-admin.png',fullPage:true});
 await page.goBack({waitUntil:'networkidle'});check('back returns workbench',new URL(page.url()).pathname==='/');check('admin back preserves film',JSON.stringify(await history())===filmBeforeAdmin);await page.goForward({waitUntil:'networkidle'});check('forward returns admin',new URL(page.url()).pathname==='/admin');await page.goto('http://host.docker.internal:19081/admin/crawling',{waitUntil:'networkidle'});check('legacy admin redirect preserved',new URL(page.url()).pathname==='/admin');
 check('zero browser errors',errors.length===0);fs.writeFileSync('/evidence/browser-results.json',JSON.stringify({passed:checks.length,checks,errors,measurements},null,2));console.log('PASS '+checks.length);await browser.close();
})().catch(async e=>{fs.writeFileSync('/evidence/browser-failure-'+run+'.json',JSON.stringify({error:e.stack,checks,errors,measurements},null,2));if(page)await page.screenshot({path:'/evidence/browser-failure-'+run+'.png',fullPage:true}).catch(()=>{});if(browser)await browser.close();console.error(e);process.exit(1)});
