const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('/qa/node_modules/playwright');
const results=require('/evidence/api-results.json'),messages=require('/source/frontend/src/shared/i18n/messages.json'),terms=require('/source/frontend/src/shared/i18n/gameTerms.json'),registry=require('/source/backend/src/main/resources/crafting/registry-v2.json');
const key='hephaistos.workbench.films.v1',checks=[],errors=[];let browser,page;
function check(n,v){assert(v,n);checks.push(n)}
const crafted=m=>m.modifierId.includes(':crafted:');
(async()=>{
 browser=await chromium.launch({headless:true});page=await(await browser.newContext({viewport:{width:1440,height:1100}})).newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://host.docker.internal:18981',{waitUntil:'networkidle'});await page.locator('.locale-selector select').selectOption('en');
 const hist=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 const current=async()=>{const h=await hist();return h.films.find(f=>f.id===h.active).frames[h.cursor].state};
 async function apply(id,category='Currency') {
  const cursor=(await hist()).cursor;await page.getByRole('tab',{name:category,exact:true}).click();await page.getByRole('button',{name:terms.en[id]?.name??registry.entries.find(e=>e.id===id).name,exact:true}).click({button:'right'});await page.locator('.item-slot').click({modifiers:['Shift']});await page.waitForFunction(({key,cursor})=>JSON.parse(localStorage.getItem(key)).cursor===cursor+1,{key,cursor});
 }
 async function restore(state,evidence) {
  const frame={state,action:evidence?evidence.action:null,...(evidence?{evidence}:{})};
  await page.evaluate(({key,frame})=>localStorage.setItem(key,JSON.stringify({version:1,films:[{id:'qa-basic-jewel',createdAt:'2026-10-04T00:00:00Z',frames:[frame]}],active:'qa-basic-jewel',cursor:0})),{key,frame});await page.reload({waitUntil:'networkidle'});await page.locator('.locale-selector select').selectOption('en');
 }
 for(const base of ['time-lost-ruby','time-lost-emerald','time-lost-diamond','time-lost-sapphire']) {
  await page.locator('.workbench-session-entry button').nth(0).click();await page.locator('#base-select').selectOption(base);await page.locator('#sapphire-rarity').selectOption('NORMAL');await page.getByRole('button',{name:messages.en['ui.place_base'],exact:false}).click();
  await page.waitForFunction(({key,id})=>JSON.parse(localStorage.getItem(key)||'null')?.films.some(f=>f.frames[0].state.baseItemId===id),{key,id:results.initials[base].state.baseItemId});check(base+' placed Normal',(await current()).rarity==='NORMAL');
  let count=0;for(const id of ['Orb_of_Transmutation','Orb_of_Augmentation','Regal_Orb','Exalted_Orb']){await apply(id);check(base+' UI generation '+id,(await current()).explicits.length===++count)}
  const beforeCrossCategory=JSON.stringify(await hist());await page.getByRole('tab',{name:'Liquid Emotions',exact:true}).click();await page.getByRole('button',{name:'Diluted Liquid Ire',exact:true}).click({button:'right'});await page.locator('.item-slot').click({modifiers:['Shift']});await page.waitForTimeout(300);check(base+' Basic Liquid UI rejection no spend',JSON.stringify(await hist())===beforeCrossCategory);
  const candidates=results.captures.filter(c=>c.base===base&&c.action.includes('LIQUID_')&&c.result.applied),seen=new Set();
  for(const capture of candidates){const outcome=capture.result.events[1].modifierId;if(seen.has(outcome))continue;seen.add(outcome);await restore(capture.before);const id=registry.entries.find(e=>e.action===capture.action).id;await apply(id,'Liquid Emotions');const actual=await current();check(base+' positive Liquid UI '+id,actual.explicits.some(crafted));check(base+' Crafted colour '+id,await page.locator('.bench-item-card .item-card__line--crafted').count()===1);check(base+' Liquid film evidence '+id,(await hist()).films[0].frames[1].evidence.assumptions.some(a=>a.id==='uniform-liquid-outcomes-v1'));await page.locator('.sapphire-craft-evidence summary').click();check(base+' probability detail '+id,(await page.locator('.sapphire-craft-evidence').innerText()).includes('%'));const before=JSON.stringify(await hist());await page.locator('.item-slot').click({modifiers:['Shift']});check(base+' repeat no spend '+id,JSON.stringify(await hist())===before);}
  const saved=JSON.stringify(await hist());await page.reload({waitUntil:'networkidle'});check(base+' film reload',JSON.stringify(await hist())===saved);await page.getByRole('button',{name:messages.en['ui.previous_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===0,key);check(base+' undo',!(await current()).explicits.some(crafted));await page.getByRole('button',{name:messages.en['ui.next_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===1,key);check(base+' redo',(await current()).explicits.some(crafted));
  const ferocity=results.captures.find(c=>c.base===base&&c.action==='ANCIENT_POTENT_LIQUID_FEROCITY'&&c.result.applied&&c.result.state.explicits.length===4);await restore(ferocity.result.state,ferocity.result);check(base+' sourced effect film',!(await page.getByRole('alert').allTextContents()).some(s=>s.includes(messages.en['notice.saved_catalog'])));
  await page.keyboard.down('Alt');check(base+' Alt affix sides',await page.locator('.bench-item-card .item-card__affix').count()===4);const ferocityDefinition=results.initials[base].modifiers[ferocity.result.events[1].modifierId];check(base+' Alt canonical source range',(await page.locator('.bench-item-card .item-card__line--crafted').innerText()).includes(ferocityDefinition.text));await page.keyboard.up('Alt');
  for(const locale of ['en','ko','zh-CN','zh-TW','ja','es']) {
   await page.locator('.locale-selector select').selectOption(locale);check(base+locale+' scope',await page.locator('.workbench-feedback').filter({hasText:messages[locale]['notice.time_lost_scope']}).isVisible());check(base+locale+' evidence',await page.locator('.sapphire-craft-evidence summary').innerText()===messages[locale]['ui.sapphire_craft_evidence']);
   for(const width of [1440,390]){await page.setViewportSize({width,height:width===1440?1100:844});check(base+locale+width+' overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'/evidence/'+base+'-'+locale+'-'+width+'.png',fullPage:true});if(width===390)await page.locator('.bench-item-card').screenshot({path:'/evidence/card-'+base+'-'+locale+'.png'})}
  }
  await page.setViewportSize({width:1440,height:1100});await page.locator('.locale-selector select').selectOption('en');
  const overflow=results.captures.find(c=>c.base===base&&c.result.applied&&c.result.assumptions.some(a=>a.id==='jewel-cap-loss-preserve-v1'));await restore(overflow.result.state,overflow.result);check(base+' overflow film exact',JSON.stringify(await current())===JSON.stringify(overflow.result.state));await page.screenshot({path:'/evidence/'+base+'-overflow.png',fullPage:true});
 }
 // Preserve the existing local orange Omen preview interaction.
 const sample=results.captures.find(c=>c.base==='time-lost-sapphire'&&c.action==='ANCIENT_POTENT_LIQUID_FEROCITY'&&c.result.applied&&c.before.explicits.length===4);await restore(sample.before);
 await page.getByRole('tab',{name:'Omen',exact:true}).click();await page.getByRole('button',{name:terms.en.Omen_of_Whittling.name,exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: empty',exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: '+terms.en.Omen_of_Whittling.name,exact:true}).click({button:'right'});await page.getByRole('tab',{name:'Currency',exact:true}).click();await page.getByRole('button',{name:terms.en.Orb_of_Annulment.name,exact:true}).click({button:'right'});check('orange Omen local preview',await page.locator('.bench-item-card [data-removal-candidate]').count()===4);await page.screenshot({path:'/evidence/omen-candidates.png',fullPage:true});
 check('zero page errors',errors.length===0);fs.writeFileSync('/evidence/browser-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));console.log('PASS '+checks.length);await browser.close();
})().catch(async e=>{fs.writeFileSync('/evidence/browser-failure-2.json',JSON.stringify({error:e.stack,checks,errors},null,2));if(page)await page.screenshot({path:'/evidence/browser-failure-2.png',fullPage:true}).catch(()=>{});if(browser)await browser.close();console.error(e);process.exit(1)});
