const fs=require('fs');
const p='frontend/src/shared/i18n/messages.json',m=JSON.parse(fs.readFileSync(p));
const text={
en:'Time-Lost Jewels: Ruby 53, Emerald 77, Sapphire 60, Diamond 160 ordinary candidates; Magic 1P/1S, Rare 2P/2S. Rare Ruby/Emerald/Sapphire support Ancient Liquid 13; Diamond supports Ancient Potent 3. One Crafted occupies an ordinary slot. Odds use disclosed 1/N after legal removal/outcome filtering; game weights are unavailable. Ancient Ferocity grants Notable resistance; Melancholy upgrades Radius to Very Large. Small/Notable and transformed damage effects are conditional text; the passive tree is not simulated. Contempt cap loss preserves existing overflow. Catalysts and Basic Liquids do not apply.',
ko:'Time-Lost Jewel: Ruby 53·Emerald 77·Sapphire 60·Diamond 160 일반 후보, Magic 1P/1S·Rare 2P/2S. Rare Ruby/Emerald/Sapphire는 Ancient Liquid 13종, Diamond는 Ancient Potent 3종을 지원합니다. Crafted 하나가 일반 슬롯을 사용합니다. 게임 weight가 없어 합법적인 제거·outcome 필터 후 공개된 1/N 모델을 사용합니다. Ancient Ferocity는 Notable Resistance, Melancholy는 Very Large Radius입니다. Small/Notable·변환 효과는 조건부 텍스트만 표시하고 passive tree는 계산하지 않습니다. Contempt 제거 후 overflow는 보존합니다. Catalyst·Basic Liquid는 적용되지 않습니다.',
'zh-CN':'Time-Lost Jewel：Ruby 53、Emerald 77、Sapphire 60、Diamond 160 个普通候选；Magic 1P/1S，Rare 2P/2S。Rare Ruby/Emerald/Sapphire 支持13种 Ancient Liquid，Diamond 支持3种 Ancient Potent。最多一个 Crafted，占用普通词缀槽。游戏权重未知，合法移除与结果筛选后使用公开1/N模型。Ancient Ferocity 给予范围内显著天赋抗性，Melancholy 将半径升级为非常大。Small/Notable及伤害转换仅显示条件，不模拟天赋树。移除 Contempt 保留已有超限词缀。Catalyst 和 Basic Liquid 不适用。',
'zh-TW':'Time-Lost Jewel：Ruby 53、Emerald 77、Sapphire 60、Diamond 160 個普通候選；Magic 1P/1S，Rare 2P/2S。Rare Ruby/Emerald/Sapphire 支援13種 Ancient Liquid，Diamond 支援3種 Ancient Potent。最多一個 Crafted，佔用普通詞綴槽。遊戲權重未知，合法移除與結果篩選後使用公開1/N模型。Ancient Ferocity 給予範圍內核心天賦抗性，Melancholy 將半徑升級為非常大。Small/Notable及傷害轉換僅顯示條件，不模擬天賦樹。移除 Contempt 保留已有超限詞綴。Catalyst 和 Basic Liquid 不適用。',
ja:'Time-Lost Jewel：Ruby 53、Emerald 77、Sapphire 60、Diamond 160 の通常候補。Magic 1P/1S、Rare 2P/2S。Rare Ruby/Emerald/Sapphire は Ancient Liquid 13種、Diamond は Ancient Potent 3種に対応。Crafted は1個で通常スロットを使います。ゲームの重みは不明で、合法な削除と結果の選別後に公開1/Nモデルを使用。Ancient Ferocity は範囲内の Notable に耐性を付与、Melancholy は Radius を Very Large に変更します。Small/Notable と変換は条件のみ表示し、パッシブツリーを計算しません。Contempt 削除後の既存超過は保持。Catalyst と Basic Liquid は対象外。',
es:'Time-Lost Jewels: Ruby 53, Emerald 77, Sapphire 60, Diamond 160 candidatos ordinarios; Magic 1P/1S, Rare 2P/2S. Rare Ruby/Emerald/Sapphire admiten Ancient Liquid 13; Diamond admite Ancient Potent 3. Un Crafted ocupa un espacio ordinario. Sin pesos del juego, se declara 1/N tras filtrar eliminaciones y resultados legales. Ancient Ferocity otorga resistencia a Notables; Melancholy mejora el radio a muy grande. Small/Notable y las conversiones se muestran como condiciones, sin simular el árbol pasivo. Al eliminar Contempt se conserva el exceso existente. Catalyst y Basic Liquid no son aplicables.'
};
const tails={en:' Ancient Liquids remain unsupported.',ko:' Ancient Liquid는 미지원입니다.','zh-CN':'Ancient Liquid 暂不支持。','zh-TW':'Ancient Liquid 暫不支援。',ja:'Ancient Liquid は未対応。',es:'Ancient Liquid no compatible.'};
for(const l of Object.keys(text)){m[l]['notice.time_lost_scope']=text[l];m[l]['notice.sapphire_scope']=m[l]['notice.sapphire_scope'].replace(tails[l],'');}
fs.writeFileSync(p,JSON.stringify(m,null,2)+'\n');
const page='frontend/src/features/crafting/CraftingPage.tsx';let s=fs.readFileSync(page,'utf8').replaceAll("t('notice.sapphire_scope')","t(catalogBase.startsWith('time-lost-') ? 'notice.time_lost_scope' : 'notice.sapphire_scope')");fs.writeFileSync(page,s);
for(const f of [p,page])fs.copyFileSync(f,'../ancient-liquid-20261004/frontend-check/'+f.slice(9));
