/* Display-only catalog; positions from the approved Currency page. No game rules. */
export const currencies = [
  {
    id: 'Orb_of_Transmutation',
    name: '진화의 오브',
    x: 29,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Orb_of_Augmentation',
    name: '확장의 오브',
    x: 29,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Orb_of_Chance',
    name: '기회의 오브',
    x: 329,
    y: 140,
    image: '/assets/currency/CurrencyUpgradeToUnique.webp',
  },
  {
    id: 'Orb_of_Annulment',
    name: '소멸의 오브',
    x: 529,
    y: 40,
    image: '/assets/currency/AnnullOrb.webp',
  },
  {
    id: 'Orb_of_Alchemy',
    name: '연금술의 오브',
    x: 329,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToRare.webp',
  },
  {
    id: 'Regal_Orb',
    name: '제왕의 오브',
    x: 29,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Exalted_Orb',
    name: '엑잘티드 오브',
    x: 29,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Chaos_Orb',
    name: '카오스 오브',
    x: 29,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Vaal_Orb',
    name: '바알 오브',
    x: 429,
    y: 40,
    image: '/assets/currency/CurrencyVaal.webp',
  },
  {
    id: 'Fracturing_Orb',
    name: '분열의 오브',
    x: 429,
    y: 140,
    image: '/assets/currency/FracturingOrb.webp',
  },
  {
    id: 'Divine_Orb',
    name: '신성한 오브',
    x: 529,
    y: 140,
    image: '/assets/currency/CurrencyModValues.webp',
  },
  {
    id: 'Mirror_of_Kalandra',
    name: '칼란드라의 거울',
    x: 379,
    y: 240,
    image: '/assets/currency/CurrencyDuplicate.webp',
  },
  {
    id: 'Arcanists_Etcher',
    name: '신비학자의 식각기',
    x: 629,
    y: 270,
    image: '/assets/currency/CurrencyWeaponMagicQuality.webp',
  },
  {
    id: 'Armourers_Scrap',
    name: '방어구 장인의 고철',
    x: 729,
    y: 270,
    image: '/assets/currency/CurrencyArmourQuality.webp',
  },
  {
    id: 'Blacksmiths_Whetstone',
    name: '대장장이의 숫돌',
    x: 829,
    y: 270,
    image: '/assets/currency/CurrencyWeaponQuality.webp',
  },
  {
    id: 'Artificers_Orb',
    name: '숙련공의 오브',
    x: 829,
    y: 140,
    image: '/assets/currency/CurrencyAddEquipmentSocket.webp',
  },
  {
    id: 'Lesser_Jewellers_Orb',
    name: '하위 쥬얼러 오브',
    x: 649,
    y: 40,
    image: '/assets/currency/CurrencyRerollSocketNumbers01.webp',
  },
  {
    id: 'Greater_Jewellers_Orb',
    name: '상위 쥬얼러 오브',
    x: 739,
    y: 40,
    image: '/assets/currency/CurrencyRerollSocketNumbers02.webp',
  },
  {
    id: 'Perfect_Jewellers_Orb',
    name: '완벽한 쥬얼러 오브',
    x: 829,
    y: 40,
    image: '/assets/currency/CurrencyRerollSocketNumbers03.webp',
  },
  {
    id: 'Gemcutters_Prism',
    name: '세공사의 프리즘',
    x: 829,
    y: 370,
    image: '/assets/currency/CurrencyGemQuality.webp',
  },
  {
    id: 'Glassblowers_Bauble',
    name: '유리직공의 방울',
    x: 729,
    y: 370,
    image: '/assets/currency/CurrencyFlaskQuality.webp',
  },
  {
    id: 'Greater_Orb_of_Transmutation',
    name: '상위 진화의 오브',
    x: 119,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Perfect_Orb_of_Transmutation',
    name: '완벽한 진화의 오브',
    x: 209,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Greater_Orb_of_Augmentation',
    name: '상위 확장의 오브',
    x: 119,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Perfect_Orb_of_Augmentation',
    name: '완벽한 확장의 오브',
    x: 209,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Greater_Regal_Orb',
    name: '상위 제왕의 오브',
    x: 119,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Perfect_Regal_Orb',
    name: '완벽한 제왕의 오브',
    x: 209,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Greater_Exalted_Orb',
    name: '상위 엑잘티드 오브',
    x: 119,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Perfect_Exalted_Orb',
    name: '완벽한 엑잘티드 오브',
    x: 209,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Greater_Chaos_Orb',
    name: '상위 카오스 오브',
    x: 119,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Perfect_Chaos_Orb',
    name: '완벽한 카오스 오브',
    x: 209,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Hinekoras_Lock',
    name: '히네코라의 머리카락',
    x: 479,
    y: 240,
    image: '/assets/currency/HinekorasLock.webp',
  },
] as const
