export const currencyNames = {
  Orb_of_Transmutation: 'Orb of Transmutation',
  Orb_of_Augmentation: 'Orb of Augmentation',
  Orb_of_Chance: 'Orb of Chance',
  Orb_of_Annulment: 'Orb of Annulment',
  Orb_of_Alchemy: 'Orb of Alchemy',
  Regal_Orb: 'Regal Orb',
  Exalted_Orb: 'Exalted Orb',
  Chaos_Orb: 'Chaos Orb',
  Vaal_Orb: 'Vaal Orb',
  Fracturing_Orb: 'Fracturing Orb',
  Divine_Orb: 'Divine Orb',
  Mirror_of_Kalandra: 'Mirror of Kalandra',
  Arcanists_Etcher: "Arcanist's Etcher",
  Armourers_Scrap: "Armourer's Scrap",
  Blacksmiths_Whetstone: "Blacksmith's Whetstone",
  Artificers_Orb: "Artificer's Orb",
  Lesser_Jewellers_Orb: "Lesser Jeweller's Orb",
  Greater_Jewellers_Orb: "Greater Jeweller's Orb",
  Perfect_Jewellers_Orb: "Perfect Jeweller's Orb",
  Gemcutters_Prism: "Gemcutter's Prism",
  Glassblowers_Bauble: "Glassblower's Bauble",
  Greater_Orb_of_Transmutation: 'Greater Orb of Transmutation',
  Perfect_Orb_of_Transmutation: 'Perfect Orb of Transmutation',
  Greater_Orb_of_Augmentation: 'Greater Orb of Augmentation',
  Perfect_Orb_of_Augmentation: 'Perfect Orb of Augmentation',
  Greater_Regal_Orb: 'Greater Regal Orb',
  Perfect_Regal_Orb: 'Perfect Regal Orb',
  Greater_Exalted_Orb: 'Greater Exalted Orb',
  Perfect_Exalted_Orb: 'Perfect Exalted Orb',
  Greater_Chaos_Orb: 'Greater Chaos Orb',
  Perfect_Chaos_Orb: 'Perfect Chaos Orb',
  Hinekoras_Lock: "Hinekora's Lock",
}
