/* Display-only catalog; positions from the approved Currency page. No game rules. */
export const currencies = [
  {
    id: 'Orb_of_Transmutation',
    x: 29,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Orb_of_Augmentation',
    x: 29,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Orb_of_Annulment',
    x: 529,
    y: 40,
    image: '/assets/currency/AnnullOrb.webp',
  },
  {
    id: 'Orb_of_Alchemy',
    x: 329,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToRare.webp',
  },
  {
    id: 'Regal_Orb',
    x: 29,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Exalted_Orb',
    x: 29,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Chaos_Orb',
    x: 29,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Vaal_Orb',
    x: 429,
    y: 40,
    image: '/assets/currency/CurrencyVaal.webp',
  },
  {
    id: 'Fracturing_Orb',
    x: 429,
    y: 140,
    image: '/assets/currency/FracturingOrb.webp',
  },
  {
    id: 'Divine_Orb',
    x: 529,
    y: 140,
    image: '/assets/currency/CurrencyModValues.webp',
  },
  {
    id: 'Greater_Orb_of_Transmutation',
    x: 119,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Perfect_Orb_of_Transmutation',
    x: 209,
    y: 40,
    image: '/assets/currency/CurrencyUpgradeToMagic.webp',
  },
  {
    id: 'Greater_Orb_of_Augmentation',
    x: 119,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Perfect_Orb_of_Augmentation',
    x: 209,
    y: 140,
    image: '/assets/currency/CurrencyAddModToMagic.webp',
  },
  {
    id: 'Greater_Regal_Orb',
    x: 119,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Perfect_Regal_Orb',
    x: 209,
    y: 240,
    image: '/assets/currency/CurrencyUpgradeMagicToRare.webp',
  },
  {
    id: 'Greater_Exalted_Orb',
    x: 119,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Perfect_Exalted_Orb',
    x: 209,
    y: 340,
    image: '/assets/currency/CurrencyAddModToRare.webp',
  },
  {
    id: 'Greater_Chaos_Orb',
    x: 119,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Perfect_Chaos_Orb',
    x: 209,
    y: 440,
    image: '/assets/currency/CurrencyRerollRare.webp',
  },
  {
    id: 'Hinekoras_Lock',
    x: 329,
    y: 140,
    image: '/assets/currency/HinekorasLock.webp',
  },
] as const
