// Display catalog only. Source pages, retrieval date and hashes: public/assets/materials/sources.json.
export const materialTabs = [
  { id: 'Currency', label: 'Currency' },
  { id: 'Essence', label: 'Essence' },
  { id: 'Omen', label: 'Omen' },
  { id: 'Catalysts', label: 'Catalysts' },
  { id: 'Liquid_Emotions', label: 'Liquid Emotions' },
] as const
export type MaterialTab = (typeof materialTabs)[number]['id']
export type Material = {
  id: string
  name: string
  category: Exclude<MaterialTab, 'Currency'>
  image: string
}
export const materials: readonly Material[] = [
  {
    id: 'Lesser_Essence_of_the_Body',
    name: 'Lesser Essence of the Body',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_the_Body.webp',
  },
  {
    id: 'Lesser_Essence_of_the_Mind',
    name: 'Lesser Essence of the Mind',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_the_Mind.webp',
  },
  {
    id: 'Lesser_Essence_of_Enhancement',
    name: 'Lesser Essence of Enhancement',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Enhancement.webp',
  },
  {
    id: 'Lesser_Essence_of_Abrasion',
    name: 'Lesser Essence of Abrasion',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Abrasion.webp',
  },
  {
    id: 'Lesser_Essence_of_Flames',
    name: 'Lesser Essence of Flames',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Flames.webp',
  },
  {
    id: 'Lesser_Essence_of_Ice',
    name: 'Lesser Essence of Ice',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Ice.webp',
  },
  {
    id: 'Lesser_Essence_of_Electricity',
    name: 'Lesser Essence of Electricity',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Electricity.webp',
  },
  {
    id: 'Lesser_Essence_of_Ruin',
    name: 'Lesser Essence of Ruin',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Ruin.webp',
  },
  {
    id: 'Lesser_Essence_of_Battle',
    name: 'Lesser Essence of Battle',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Battle.webp',
  },
  {
    id: 'Lesser_Essence_of_Sorcery',
    name: 'Lesser Essence of Sorcery',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Sorcery.webp',
  },
  {
    id: 'Lesser_Essence_of_Haste',
    name: 'Lesser Essence of Haste',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Haste.webp',
  },
  {
    id: 'Lesser_Essence_of_the_Infinite',
    name: 'Lesser Essence of the Infinite',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_the_Infinite.webp',
  },
  {
    id: 'Essence_of_the_Body',
    name: 'Essence of the Body',
    category: 'Essence',
    image: '/assets/materials/Essence_of_the_Body.webp',
  },
  {
    id: 'Essence_of_the_Mind',
    name: 'Essence of the Mind',
    category: 'Essence',
    image: '/assets/materials/Essence_of_the_Mind.webp',
  },
  {
    id: 'Essence_of_Enhancement',
    name: 'Essence of Enhancement',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Enhancement.webp',
  },
  {
    id: 'Essence_of_Abrasion',
    name: 'Essence of Abrasion',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Abrasion.webp',
  },
  {
    id: 'Essence_of_Flames',
    name: 'Essence of Flames',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Flames.webp',
  },
  {
    id: 'Essence_of_Ice',
    name: 'Essence of Ice',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Ice.webp',
  },
  {
    id: 'Essence_of_Electricity',
    name: 'Essence of Electricity',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Electricity.webp',
  },
  {
    id: 'Essence_of_Ruin',
    name: 'Essence of Ruin',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Ruin.webp',
  },
  {
    id: 'Essence_of_Battle',
    name: 'Essence of Battle',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Battle.webp',
  },
  {
    id: 'Essence_of_Sorcery',
    name: 'Essence of Sorcery',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Sorcery.webp',
  },
  {
    id: 'Essence_of_Haste',
    name: 'Essence of Haste',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Haste.webp',
  },
  {
    id: 'Essence_of_the_Infinite',
    name: 'Essence of the Infinite',
    category: 'Essence',
    image: '/assets/materials/Essence_of_the_Infinite.webp',
  },
  {
    id: 'Greater_Essence_of_the_Body',
    name: 'Greater Essence of the Body',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_the_Body.webp',
  },
  {
    id: 'Greater_Essence_of_the_Mind',
    name: 'Greater Essence of the Mind',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_the_Mind.webp',
  },
  {
    id: 'Greater_Essence_of_Enhancement',
    name: 'Greater Essence of Enhancement',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Enhancement.webp',
  },
  {
    id: 'Greater_Essence_of_Abrasion',
    name: 'Greater Essence of Abrasion',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Abrasion.webp',
  },
  {
    id: 'Greater_Essence_of_Flames',
    name: 'Greater Essence of Flames',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Flames.webp',
  },
  {
    id: 'Greater_Essence_of_Ice',
    name: 'Greater Essence of Ice',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Ice.webp',
  },
  {
    id: 'Greater_Essence_of_Electricity',
    name: 'Greater Essence of Electricity',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Electricity.webp',
  },
  {
    id: 'Greater_Essence_of_Ruin',
    name: 'Greater Essence of Ruin',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Ruin.webp',
  },
  {
    id: 'Greater_Essence_of_Battle',
    name: 'Greater Essence of Battle',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Battle.webp',
  },
  {
    id: 'Greater_Essence_of_Sorcery',
    name: 'Greater Essence of Sorcery',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Sorcery.webp',
  },
  {
    id: 'Greater_Essence_of_Haste',
    name: 'Greater Essence of Haste',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Haste.webp',
  },
  {
    id: 'Greater_Essence_of_the_Infinite',
    name: 'Greater Essence of the Infinite',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_the_Infinite.webp',
  },
  {
    id: 'Perfect_Essence_of_the_Body',
    name: 'Perfect Essence of the Body',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_the_Body.webp',
  },
  {
    id: 'Perfect_Essence_of_the_Mind',
    name: 'Perfect Essence of the Mind',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_the_Mind.webp',
  },
  {
    id: 'Perfect_Essence_of_Enhancement',
    name: 'Perfect Essence of Enhancement',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Enhancement.webp',
  },
  {
    id: 'Perfect_Essence_of_Abrasion',
    name: 'Perfect Essence of Abrasion',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Abrasion.webp',
  },
  {
    id: 'Perfect_Essence_of_Flames',
    name: 'Perfect Essence of Flames',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Flames.webp',
  },
  {
    id: 'Perfect_Essence_of_Ice',
    name: 'Perfect Essence of Ice',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Ice.webp',
  },
  {
    id: 'Perfect_Essence_of_Electricity',
    name: 'Perfect Essence of Electricity',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Electricity.webp',
  },
  {
    id: 'Perfect_Essence_of_Ruin',
    name: 'Perfect Essence of Ruin',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Ruin.webp',
  },
  {
    id: 'Perfect_Essence_of_Battle',
    name: 'Perfect Essence of Battle',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Battle.webp',
  },
  {
    id: 'Perfect_Essence_of_Sorcery',
    name: 'Perfect Essence of Sorcery',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Sorcery.webp',
  },
  {
    id: 'Perfect_Essence_of_Haste',
    name: 'Perfect Essence of Haste',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Haste.webp',
  },
  {
    id: 'Perfect_Essence_of_the_Infinite',
    name: 'Perfect Essence of the Infinite',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_the_Infinite.webp',
  },
  {
    id: 'Lesser_Essence_of_Seeking',
    name: 'Lesser Essence of Seeking',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Seeking.webp',
  },
  {
    id: 'Essence_of_Seeking',
    name: 'Essence of Seeking',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Seeking.webp',
  },
  {
    id: 'Greater_Essence_of_Seeking',
    name: 'Greater Essence of Seeking',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Seeking.webp',
  },
  {
    id: 'Perfect_Essence_of_Seeking',
    name: 'Perfect Essence of Seeking',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Seeking.webp',
  },
  {
    id: 'Essence_of_Hysteria',
    name: 'Essence of Hysteria',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Hysteria.webp',
  },
  {
    id: 'Essence_of_Delirium',
    name: 'Essence of Delirium',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Delirium.webp',
  },
  {
    id: 'Essence_of_Horror',
    name: 'Essence of Horror',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Horror.webp',
  },
  {
    id: 'Essence_of_Insanity',
    name: 'Essence of Insanity',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Insanity.webp',
  },
  {
    id: 'Essence_of_the_Abyss',
    name: 'Essence of the Abyss',
    category: 'Essence',
    image: '/assets/materials/Essence_of_the_Abyss.webp',
  },
  {
    id: 'Essence_of_the_Breach',
    name: 'Essence of the Breach',
    category: 'Essence',
    image: '/assets/materials/Essence_of_the_Breach.webp',
  },
  {
    id: 'Lesser_Essence_of_Insulation',
    name: 'Lesser Essence of Insulation',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Insulation.webp',
  },
  {
    id: 'Essence_of_Insulation',
    name: 'Essence of Insulation',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Insulation.webp',
  },
  {
    id: 'Greater_Essence_of_Insulation',
    name: 'Greater Essence of Insulation',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Insulation.webp',
  },
  {
    id: 'Perfect_Essence_of_Insulation',
    name: 'Perfect Essence of Insulation',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Insulation.webp',
  },
  {
    id: 'Lesser_Essence_of_Thawing',
    name: 'Lesser Essence of Thawing',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Thawing.webp',
  },
  {
    id: 'Essence_of_Thawing',
    name: 'Essence of Thawing',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Thawing.webp',
  },
  {
    id: 'Greater_Essence_of_Thawing',
    name: 'Greater Essence of Thawing',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Thawing.webp',
  },
  {
    id: 'Perfect_Essence_of_Thawing',
    name: 'Perfect Essence of Thawing',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Thawing.webp',
  },
  {
    id: 'Lesser_Essence_of_Grounding',
    name: 'Lesser Essence of Grounding',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Grounding.webp',
  },
  {
    id: 'Essence_of_Grounding',
    name: 'Essence of Grounding',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Grounding.webp',
  },
  {
    id: 'Greater_Essence_of_Grounding',
    name: 'Greater Essence of Grounding',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Grounding.webp',
  },
  {
    id: 'Perfect_Essence_of_Grounding',
    name: 'Perfect Essence of Grounding',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Grounding.webp',
  },
  {
    id: 'Lesser_Essence_of_Alacrity',
    name: 'Lesser Essence of Alacrity',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Alacrity.webp',
  },
  {
    id: 'Essence_of_Alacrity',
    name: 'Essence of Alacrity',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Alacrity.webp',
  },
  {
    id: 'Greater_Essence_of_Alacrity',
    name: 'Greater Essence of Alacrity',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Alacrity.webp',
  },
  {
    id: 'Perfect_Essence_of_Alacrity',
    name: 'Perfect Essence of Alacrity',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Alacrity.webp',
  },
  {
    id: 'Lesser_Essence_of_Opulence',
    name: 'Lesser Essence of Opulence',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Opulence.webp',
  },
  {
    id: 'Essence_of_Opulence',
    name: 'Essence of Opulence',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Opulence.webp',
  },
  {
    id: 'Greater_Essence_of_Opulence',
    name: 'Greater Essence of Opulence',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Opulence.webp',
  },
  {
    id: 'Perfect_Essence_of_Opulence',
    name: 'Perfect Essence of Opulence',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Opulence.webp',
  },
  {
    id: 'Lesser_Essence_of_Command',
    name: 'Lesser Essence of Command',
    category: 'Essence',
    image: '/assets/materials/Lesser_Essence_of_Command.webp',
  },
  {
    id: 'Essence_of_Command',
    name: 'Essence of Command',
    category: 'Essence',
    image: '/assets/materials/Essence_of_Command.webp',
  },
  {
    id: 'Greater_Essence_of_Command',
    name: 'Greater Essence of Command',
    category: 'Essence',
    image: '/assets/materials/Greater_Essence_of_Command.webp',
  },
  {
    id: 'Perfect_Essence_of_Command',
    name: 'Perfect Essence of Command',
    category: 'Essence',
    image: '/assets/materials/Perfect_Essence_of_Command.webp',
  },
  {
    id: 'Runic_Alloy',
    name: 'Runic Alloy',
    category: 'Essence',
    image: '/assets/materials/Runic_Alloy.webp',
  },
  {
    id: 'Adaptive_Alloy',
    name: 'Adaptive Alloy',
    category: 'Essence',
    image: '/assets/materials/Adaptive_Alloy.webp',
  },
  {
    id: 'Protective_Alloy',
    name: 'Protective Alloy',
    category: 'Essence',
    image: '/assets/materials/Protective_Alloy.webp',
  },
  {
    id: 'Expansive_Alloy',
    name: 'Expansive Alloy',
    category: 'Essence',
    image: '/assets/materials/Expansive_Alloy.webp',
  },
  {
    id: 'Swift_Alloy',
    name: 'Swift Alloy',
    category: 'Essence',
    image: '/assets/materials/Swift_Alloy.webp',
  },
  {
    id: 'Cyclonic_Alloy',
    name: 'Cyclonic Alloy',
    category: 'Essence',
    image: '/assets/materials/Cyclonic_Alloy.webp',
  },
  {
    id: 'Prismatic_Alloy',
    name: 'Prismatic Alloy',
    category: 'Essence',
    image: '/assets/materials/Prismatic_Alloy.webp',
  },
  {
    id: 'Mystic_Alloy',
    name: 'Mystic Alloy',
    category: 'Essence',
    image: '/assets/materials/Mystic_Alloy.webp',
  },
  {
    id: 'Sovereign_Alloy',
    name: 'Sovereign Alloy',
    category: 'Essence',
    image: '/assets/materials/Sovereign_Alloy.webp',
  },
  {
    id: 'Celestial_Alloy',
    name: 'Celestial Alloy',
    category: 'Essence',
    image: '/assets/materials/Celestial_Alloy.webp',
  },
  {
    id: 'Transcendent_Alloy',
    name: 'Transcendent Alloy',
    category: 'Essence',
    image: '/assets/materials/Transcendent_Alloy.webp',
  },
  {
    id: 'The_Runebinders_Alloy',
    name: "The Runebinder's Alloy",
    category: 'Essence',
    image: '/assets/materials/The_Runebinders_Alloy.webp',
  },
  {
    id: 'The_Runefathers_Alloy',
    name: "The Runefather's Alloy",
    category: 'Essence',
    image: '/assets/materials/The_Runefathers_Alloy.webp',
  },
  {
    id: 'Aldurs_Saga',
    name: "Aldur's Saga",
    category: 'Omen',
    image: '/assets/materials/Aldurs_Saga.webp',
  },
  {
    id: 'Medveds_Saga',
    name: "Medved's Saga",
    category: 'Omen',
    image: '/assets/materials/Medveds_Saga.webp',
  },
  {
    id: 'Voranas_Saga',
    name: "Vorana's Saga",
    category: 'Omen',
    image: '/assets/materials/Voranas_Saga.webp',
  },
  {
    id: 'Uhtreds_Saga',
    name: "Uhtred's Saga",
    category: 'Omen',
    image: '/assets/materials/Uhtreds_Saga.webp',
  },
  {
    id: 'Olroths_Saga',
    name: "Olroth's Saga",
    category: 'Omen',
    image: '/assets/materials/Olroths_Saga.webp',
  },
  {
    id: 'Omen_of_Refreshment',
    name: 'Omen of Refreshment',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Refreshment.webp',
  },
  {
    id: 'Omen_of_Resurgence',
    name: 'Omen of Resurgence',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Resurgence.webp',
  },
  {
    id: 'Omen_of_Amelioration',
    name: 'Omen of Amelioration',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Amelioration.webp',
  },
  {
    id: 'Omen_of_Whittling',
    name: 'Omen of Whittling',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Whittling.webp',
  },
  {
    id: 'Omen_of_Sinistral_Erasure',
    name: 'Omen of Sinistral Erasure',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Erasure.webp',
  },
  {
    id: 'Omen_of_Dextral_Erasure',
    name: 'Omen of Dextral Erasure',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Erasure.webp',
  },
  {
    id: 'Omen_of_Sinistral_Alchemy',
    name: 'Omen of Sinistral Alchemy',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Alchemy.webp',
  },
  {
    id: 'Omen_of_Dextral_Alchemy',
    name: 'Omen of Dextral Alchemy',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Alchemy.webp',
  },
  {
    id: 'Omen_of_Sinistral_Coronation',
    name: 'Omen of Sinistral Coronation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Coronation.webp',
  },
  {
    id: 'Omen_of_Dextral_Coronation',
    name: 'Omen of Dextral Coronation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Coronation.webp',
  },
  {
    id: 'Omen_of_Corruption',
    name: 'Omen of Corruption',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Corruption.webp',
  },
  {
    id: 'Omen_of_Greater_Exaltation',
    name: 'Omen of Greater Exaltation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Greater_Exaltation.webp',
  },
  {
    id: 'Omen_of_Sinistral_Exaltation',
    name: 'Omen of Sinistral Exaltation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Exaltation.webp',
  },
  {
    id: 'Omen_of_Dextral_Exaltation',
    name: 'Omen of Dextral Exaltation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Exaltation.webp',
  },
  {
    id: 'Omen_of_Greater_Annulment',
    name: 'Omen of Greater Annulment',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Greater_Annulment.webp',
  },
  {
    id: 'Omen_of_Sinistral_Annulment',
    name: 'Omen of Sinistral Annulment',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Annulment.webp',
  },
  {
    id: 'Omen_of_Dextral_Annulment',
    name: 'Omen of Dextral Annulment',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Annulment.webp',
  },
  {
    id: 'Omen_of_Answered_Prayers',
    name: 'Omen of Answered Prayers',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Answered_Prayers.webp',
  },
  {
    id: 'Omen_of_Secret_Compartments',
    name: 'Omen of Secret Compartments',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Secret_Compartments.webp',
  },
  {
    id: 'Omen_of_the_Hunt',
    name: 'Omen of the Hunt',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Hunt.webp',
  },
  {
    id: 'Omen_of_Reinforcements',
    name: 'Omen of Reinforcements',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Reinforcements.webp',
  },
  {
    id: 'Omen_of_Homogenising_Exaltation',
    name: 'Omen of Homogenising Exaltation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Homogenising_Exaltation.webp',
  },
  {
    id: 'Omen_of_Homogenising_Coronation',
    name: 'Omen of Homogenising Coronation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Homogenising_Coronation.webp',
  },
  {
    id: 'Omen_of_Gambling',
    name: 'Omen of Gambling',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Gambling.webp',
  },
  {
    id: 'Omen_of_Bartering',
    name: 'Omen of Bartering',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Bartering.webp',
  },
  {
    id: 'Omen_of_Recombination',
    name: 'Omen of Recombination',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Recombination.webp',
  },
  {
    id: 'Omen_of_the_Blessed',
    name: 'Omen of the Blessed',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Blessed.webp',
  },
  {
    id: 'Omen_of_Chaotic_Rarity',
    name: 'Omen of Chaotic Rarity',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Chaotic_Rarity.webp',
  },
  {
    id: 'Omen_of_Chaotic_Quantity',
    name: 'Omen of Chaotic Quantity',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Chaotic_Quantity.webp',
  },
  {
    id: 'Omen_of_Chaotic_Monsters',
    name: 'Omen of Chaotic Monsters',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Chaotic_Monsters.webp',
  },
  {
    id: 'Omen_of_Chaotic_Effectiveness',
    name: 'Omen of Chaotic Effectiveness',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Chaotic_Effectiveness.webp',
  },
  {
    id: 'Omen_of_Chance',
    name: 'Omen of Chance',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Chance.webp',
  },
  {
    id: 'Omen_of_the_Ancients',
    name: 'Omen of the Ancients',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Ancients.webp',
  },
  {
    id: 'Omen_of_Sanctification',
    name: 'Omen of Sanctification',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sanctification.webp',
  },
  {
    id: 'Omen_of_Dextral_Crystallisation',
    name: 'Omen of Dextral Crystallisation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Crystallisation.webp',
  },
  {
    id: 'Omen_of_Sinistral_Crystallisation',
    name: 'Omen of Sinistral Crystallisation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Crystallisation.webp',
  },
  {
    id: 'Omen_of_Catalysing_Exaltation',
    name: 'Omen of Catalysing Exaltation',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Catalysing_Exaltation.webp',
  },
  {
    id: 'Omen_of_Abyssal_Echoes',
    name: 'Omen of Abyssal Echoes',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Abyssal_Echoes.webp',
  },
  {
    id: 'Omen_of_the_Sovereign',
    name: 'Omen of the Sovereign',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Sovereign.webp',
  },
  {
    id: 'Omen_of_the_Liege',
    name: 'Omen of the Liege',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Liege.webp',
  },
  {
    id: 'Omen_of_the_Blackblooded',
    name: 'Omen of the Blackblooded',
    category: 'Omen',
    image: '/assets/materials/Omen_of_the_Blackblooded.webp',
  },
  {
    id: 'Omen_of_Putrefaction',
    name: 'Omen of Putrefaction',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Putrefaction.webp',
  },
  {
    id: 'Omen_of_Light',
    name: 'Omen of Light',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Light.webp',
  },
  {
    id: 'Omen_of_Sinistral_Necromancy',
    name: 'Omen of Sinistral Necromancy',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Sinistral_Necromancy.webp',
  },
  {
    id: 'Omen_of_Dextral_Necromancy',
    name: 'Omen of Dextral Necromancy',
    category: 'Omen',
    image: '/assets/materials/Omen_of_Dextral_Necromancy.webp',
  },
  {
    id: 'Flesh_Catalyst',
    name: 'Flesh Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Flesh_Catalyst.webp',
  },
  {
    id: 'Neural_Catalyst',
    name: 'Neural Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Neural_Catalyst.webp',
  },
  {
    id: 'Carapace_Catalyst',
    name: 'Carapace Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Carapace_Catalyst.webp',
  },
  {
    id: 'Uul-Netols_Catalyst',
    name: "Uul-Netol's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Uul-Netols_Catalyst.webp',
  },
  {
    id: 'Xophs_Catalyst',
    name: "Xoph's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Xophs_Catalyst.webp',
  },
  {
    id: 'Tuls_Catalyst',
    name: "Tul's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Tuls_Catalyst.webp',
  },
  {
    id: 'Eshs_Catalyst',
    name: "Esh's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Eshs_Catalyst.webp',
  },
  {
    id: 'Chayulas_Catalyst',
    name: "Chayula's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Chayulas_Catalyst.webp',
  },
  {
    id: 'Reaver_Catalyst',
    name: 'Reaver Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Reaver_Catalyst.webp',
  },
  {
    id: 'Sibilant_Catalyst',
    name: 'Sibilant Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Sibilant_Catalyst.webp',
  },
  {
    id: 'Skittering_Catalyst',
    name: 'Skittering Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Skittering_Catalyst.webp',
  },
  {
    id: 'Adaptive_Catalyst',
    name: 'Adaptive Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Adaptive_Catalyst.webp',
  },
  {
    id: 'Necrotic_Catalyst',
    name: 'Necrotic Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Necrotic_Catalyst.webp',
  },
  {
    id: 'Refined_Flesh_Catalyst',
    name: 'Refined Flesh Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Flesh_Catalyst.webp',
  },
  {
    id: 'Refined_Neural_Catalyst',
    name: 'Refined Neural Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Neural_Catalyst.webp',
  },
  {
    id: 'Refined_Carapace_Catalyst',
    name: 'Refined Carapace Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Carapace_Catalyst.webp',
  },
  {
    id: 'Refined_Uul-Netols_Catalyst',
    name: "Refined Uul-Netol's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Refined_Uul-Netols_Catalyst.webp',
  },
  {
    id: 'Refined_Xophs_Catalyst',
    name: "Refined Xoph's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Refined_Xophs_Catalyst.webp',
  },
  {
    id: 'Refined_Tuls_Catalyst',
    name: "Refined Tul's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Refined_Tuls_Catalyst.webp',
  },
  {
    id: 'Refined_Eshs_Catalyst',
    name: "Refined Esh's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Refined_Eshs_Catalyst.webp',
  },
  {
    id: 'Refined_Chayulas_Catalyst',
    name: "Refined Chayula's Catalyst",
    category: 'Catalysts',
    image: '/assets/materials/Refined_Chayulas_Catalyst.webp',
  },
  {
    id: 'Refined_Reaver_Catalyst',
    name: 'Refined Reaver Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Reaver_Catalyst.webp',
  },
  {
    id: 'Refined_Sibilant_Catalyst',
    name: 'Refined Sibilant Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Sibilant_Catalyst.webp',
  },
  {
    id: 'Refined_Skittering_Catalyst',
    name: 'Refined Skittering Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Skittering_Catalyst.webp',
  },
  {
    id: 'Refined_Adaptive_Catalyst',
    name: 'Refined Adaptive Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Adaptive_Catalyst.webp',
  },
  {
    id: 'Refined_Necrotic_Catalyst',
    name: 'Refined Necrotic Catalyst',
    category: 'Catalysts',
    image: '/assets/materials/Refined_Necrotic_Catalyst.webp',
  },
  {
    id: 'Diluted_Liquid_Ire',
    name: 'Diluted Liquid Ire',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Diluted_Liquid_Ire.webp',
  },
  {
    id: 'Diluted_Liquid_Guilt',
    name: 'Diluted Liquid Guilt',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Diluted_Liquid_Guilt.webp',
  },
  {
    id: 'Diluted_Liquid_Greed',
    name: 'Diluted Liquid Greed',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Diluted_Liquid_Greed.webp',
  },
  {
    id: 'Liquid_Paranoia',
    name: 'Liquid Paranoia',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Liquid_Paranoia.webp',
  },
  {
    id: 'Liquid_Envy',
    name: 'Liquid Envy',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Liquid_Envy.webp',
  },
  {
    id: 'Liquid_Disgust',
    name: 'Liquid Disgust',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Liquid_Disgust.webp',
  },
  {
    id: 'Liquid_Despair',
    name: 'Liquid Despair',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Liquid_Despair.webp',
  },
  {
    id: 'Concentrated_Liquid_Fear',
    name: 'Concentrated Liquid Fear',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Concentrated_Liquid_Fear.webp',
  },
  {
    id: 'Concentrated_Liquid_Suffering',
    name: 'Concentrated Liquid Suffering',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Concentrated_Liquid_Suffering.webp',
  },
  {
    id: 'Concentrated_Liquid_Isolation',
    name: 'Concentrated Liquid Isolation',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Concentrated_Liquid_Isolation.webp',
  },
  {
    id: 'Ancient_Diluted_Liquid_Ire',
    name: 'Ancient Diluted Liquid Ire',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Diluted_Liquid_Ire.webp',
  },
  {
    id: 'Ancient_Diluted_Liquid_Guilt',
    name: 'Ancient Diluted Liquid Guilt',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Diluted_Liquid_Guilt.webp',
  },
  {
    id: 'Ancient_Diluted_Liquid_Greed',
    name: 'Ancient Diluted Liquid Greed',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Diluted_Liquid_Greed.webp',
  },
  {
    id: 'Ancient_Liquid_Paranoia',
    name: 'Ancient Liquid Paranoia',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Liquid_Paranoia.webp',
  },
  {
    id: 'Ancient_Liquid_Envy',
    name: 'Ancient Liquid Envy',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Liquid_Envy.webp',
  },
  {
    id: 'Ancient_Liquid_Disgust',
    name: 'Ancient Liquid Disgust',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Liquid_Disgust.webp',
  },
  {
    id: 'Ancient_Liquid_Despair',
    name: 'Ancient Liquid Despair',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Liquid_Despair.webp',
  },
  {
    id: 'Ancient_Concentrated_Liquid_Fear',
    name: 'Ancient Concentrated Liquid Fear',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Concentrated_Liquid_Fear.webp',
  },
  {
    id: 'Ancient_Concentrated_Liquid_Suffering',
    name: 'Ancient Concentrated Liquid Suffering',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Concentrated_Liquid_Suffering.webp',
  },
  {
    id: 'Ancient_Concentrated_Liquid_Isolation',
    name: 'Ancient Concentrated Liquid Isolation',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Concentrated_Liquid_Isolation.webp',
  },
  {
    id: 'Potent_Liquid_Melancholy',
    name: 'Potent Liquid Melancholy',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Potent_Liquid_Melancholy.webp',
  },
  {
    id: 'Potent_Liquid_Ferocity',
    name: 'Potent Liquid Ferocity',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Potent_Liquid_Ferocity.webp',
  },
  {
    id: 'Potent_Liquid_Contempt',
    name: 'Potent Liquid Contempt',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Potent_Liquid_Contempt.webp',
  },
  {
    id: 'Ancient_Potent_Liquid_Melancholy',
    name: 'Ancient Potent Liquid Melancholy',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Potent_Liquid_Melancholy.webp',
  },
  {
    id: 'Ancient_Potent_Liquid_Ferocity',
    name: 'Ancient Potent Liquid Ferocity',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Potent_Liquid_Ferocity.webp',
  },
  {
    id: 'Ancient_Potent_Liquid_Contempt',
    name: 'Ancient Potent Liquid Contempt',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Ancient_Potent_Liquid_Contempt.webp',
  },
  {
    id: 'Liquid_Verisium',
    name: 'Liquid Verisium',
    category: 'Liquid_Emotions',
    image: '/assets/materials/Liquid_Verisium.webp',
  },
]
