const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('/qa/node_modules/playwright');
const messages=require('/source/frontend/src/shared/i18n/messages.json'),terms=require('/source/frontend/src/shared/i18n/gameTerms.json');
const apiResults=require('/evidence/api-results.json');
const key='hephaistos.workbench.films.v1',checks=[],errors=[];let browser,page;
function check(n,v){assert(v,n);checks.push(n)}
(async()=>{
browser=await chromium.launch({headless:true});page=await(await browser.newContext({viewport:{width:1440,height:1100}})).newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://host.docker.internal:18781',{waitUntil:'networkidle'});await page.locator('.locale-selector select').selectOption('en');
const hist=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
const current=async()=>{const h=await hist();return h.films.find(f=>f.id===h.active).frames[h.cursor].state};
await page.locator('.workbench-session-entry button').nth(0).click();await page.locator('#base-select').selectOption('sapphire');await page.locator('#sapphire-rarity').selectOption('NORMAL');
await page.locator('#starting-quality-type').selectOption('SIBILANT');await page.locator('#starting-quality-amount').fill('20');await page.getByRole('button',{name:messages.en['ui.place_base'],exact:false}).click();
await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)||'null')?.films.some(f=>f.frames[0].state.baseItemId==='Metadata/Items/Jewels/JewelInt'),key);check('Normal Sapphire placed',(await current()).rarity==='NORMAL');
async function apply(id,category='Currency') {const cursor=(await hist()).cursor;await page.getByRole('tab',{name:category,exact:true}).click();await page.getByRole('button',{name:(terms.en[id]?.name ?? require("/source/backend/src/main/resources/crafting/registry-v2.json").entries.find(e=>e.id===id).name),exact:true}).click({button:'right'});await page.locator('.item-slot').click({modifiers:['Shift']});await page.waitForFunction(({key,cursor})=>JSON.parse(localStorage.getItem(key)).cursor===cursor+1,{key,cursor});}
let expectedCount=0;for(const id of ['Orb_of_Transmutation','Orb_of_Augmentation','Regal_Orb','Exalted_Orb']){await apply(id);check('UI positive '+id,(await current()).explicits.length===++expectedCount)}
check('UI four-slot rare',(await current()).rarity==='RARE'&&(await current()).explicits.length===4);check('generation evidence localized',await page.locator('.sapphire-craft-evidence summary').innerText()===messages.en['ui.sapphire_craft_evidence']);await page.screenshot({path:'/evidence/generation-1440.png',fullPage:true});
await page.getByRole('tab',{name:'Omen',exact:true}).click();await page.getByRole('button',{name:terms.en.Omen_of_Whittling.name,exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: empty',exact:true}).click();await page.getByRole('button',{name:'Favorite slot 1: '+terms.en.Omen_of_Whittling.name,exact:true}).click({button:'right'});await page.getByRole('tab',{name:'Currency',exact:true}).click();await page.getByRole('button',{name:terms.en.Orb_of_Annulment.name,exact:true}).click({button:'right'});check('Omen local preview four candidates',await page.locator('.bench-item-card [data-removal-candidate]').count()===4);await page.screenshot({path:'/evidence/omen-candidates.png',fullPage:true});
async function restore(state){await page.evaluate(({key,state})=>localStorage.setItem(key,JSON.stringify({version:1,films:[{id:'qa-sapphire',createdAt:'2026-10-04T00:00:00Z',frames:[{state,action:null}]}],active:'qa-sapphire',cursor:0})),{key,state});await page.reload({waitUntil:'networkidle'});await page.locator('.locale-selector select').selectOption('en');}
const liquidCaptures=apiResults.captures.filter(c=>c.action.includes('LIQUID_')&&c.result.applied);
let craftedState;
for(const capture of liquidCaptures){await restore(capture.before);const id=Object.entries(require('/source/backend/src/main/resources/crafting/registry-v2.json').entries).map(([,e])=>e).find(e=>e.action===capture.action).id;await apply(id,'Liquid Emotions');craftedState=await current();check('Liquid UI positive '+id,craftedState.explicits.some(m=>m.modifierId.startsWith('sapphire:crafted:')));check('Crafted lighter blue '+id,await page.locator('.bench-item-card .item-card__line--crafted').count()===1);await page.locator('.sapphire-craft-evidence summary').click();check('Liquid probabilities visible '+id,(await page.locator('.sapphire-craft-evidence').innerText()).includes('%'));const before=JSON.stringify(await hist());await page.locator('.item-slot').click({modifiers:['Shift']});check('repeat Liquid no frame '+id,JSON.stringify(await hist())===before);}
const stored=JSON.stringify(await hist());await page.reload({waitUntil:'networkidle'});check('Crafted film reload exact',JSON.stringify(await hist())===stored);await page.getByRole('button',{name:messages.en['ui.previous_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===0,key);check('undo Crafted gone',!(await current()).explicits.some(m=>m.modifierId.startsWith('sapphire:crafted:')));await page.getByRole('button',{name:messages.en['ui.next_crafting_step'],exact:true}).click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).cursor===1,key);check('redo Crafted restored',(await current()).explicits.some(m=>m.modifierId.startsWith('sapphire:crafted:')));
await page.keyboard.down('Alt');check('Alt source range visible',await page.locator('.bench-item-card .item-card__modifier-detail summary').count()===4);await page.keyboard.up('Alt');
for(const locale of ['en','ko','zh-CN','zh-TW','ja','es']){await page.locator('.locale-selector select').selectOption(locale);check(locale+' scope',await page.locator('.workbench-feedback').filter({hasText:messages[locale]['notice.sapphire_scope']}).isVisible());check(locale+' evidence title',await page.locator('.sapphire-craft-evidence summary').innerText()===messages[locale]['ui.sapphire_craft_evidence']);for(const width of [1440,390]){await page.setViewportSize({width,height:width===1440?1100:844});check(locale+width+' no overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'/evidence/'+locale+'-'+width+'.png',fullPage:true})}check(locale+' quality20',(await current()).catalystQuality.amount===20)}
check('zero page errors',errors.length===0);fs.writeFileSync('/evidence/browser-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));console.log('PASS '+checks.length);await browser.close();
})().catch(async e=>{fs.writeFileSync('/evidence/browser-failure.json',JSON.stringify({error:e.stack,checks,errors},null,2));if(page)await page.screenshot({path:'/evidence/browser-failure.png',fullPage:true}).catch(()=>{});if(browser)await browser.close();console.error(e);process.exit(1)});
